# Generated by Django 4.2.1 on 2023-07-06 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photourl',
            old_name='catalogo',
            new_name='objeto',
        ),
    ]
