# Generated by Django 4.2.1 on 2023-07-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rna', '0003_rename_arn_rna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rna',
            name='dataRnaUrl',
        ),
    ]
