# Generated by Django 4.2.1 on 2023-08-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rna', '0004_remove_rna_datarnaurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rna',
            old_name='configRnaUrl',
            new_name='configRna',
        ),
    ]
