# Generated by Django 4.2.1 on 2023-08-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rna', '0005_rename_configrnaurl_rna_configrna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rna',
            name='configRna',
        ),
    ]
